name: "Setup release repository"
description: "Initial release-repo setup action that configures git identity for automated release commits."
runs:
  using: "composite"
  steps:
    - name: Configure git bot
      uses: dsanroman96/workflow-templates/actions/common/configure-git-bot@main
